name: Trigger GitLab Pull Mirror

on:
  push:
    branches:
      - main   # change if needed

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pull
        run: |
          curl --request POST \
               --header "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" \
               "https://gitlab.com/api/v4/projects/73038362/mirror/pull"

