name: Mirror to GitLab

on:
  push:
    branches:
      - main   # or your branch name (e.g., "feature/*")

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push changes to GitLab
        env:
          TOKEN: ${{ secrets.GH_PAT }}   # your GitHub PAT stored in secrets
        run: |
          git remote add gitlab origin https://x-access-token:${GITLAB_TOKEN}@github.com/Mahendra08382/gitlab_action.git
          git push gitlab HEAD:main
